
server:
  servlet:
    context-path: /
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace

spring:
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  #禁用默认的favicon.ico图标
  mvc:
    favicon:
      enabled: false
  aop:
    proxy-target-class: true
  # 设置静态文件路径，js,css等
#  mvc:
#    static-path-pattern: /assets/**
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  resource:
#    static-locations: classpath:/assets/

  profiles:
    #active: dev
    active: @spring.profiles.active@
